services:
  client:
    image: abc122/multi-container:client
    mem_limit: 128m
    hostname: client
  server:
    image: abc122/multi-comtainer:server
    mem_limit: 128m
    hostname: api  # can also remove this and name server as api, will work the same
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: abc122/multi-container:worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: abc122/multi-container:nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
      