name: deploy-stage
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-test npm run test 
        # -e CI=true stops it after test is done and dose not wait for inputs
      
      # building the containers 
      - run: docker build -t abc122/multi-client ./client
      - run: docker build -t abc122/multi-nginx ./nginx
      - run: docker build -t abc122/multi-server ./server
      - run: docker build -t abc122/multi-worker ./worker

      #login to docker hub
      - name: DockerHub Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin 
      # push to docker hub
      - run: docker push multi-container-test/abc122/multi-client
      - run: docker push multi-container-test/abc122/multi-nginx
      - run: docker push multi-container-test/abc122/multi-server
      - run: docker push multi-container-test/abc122/multi-worker