name: deploy-stage
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-test npm run test 
        # -e CI=true stops it after test is done and dose not wait for inputs
      
      # building the containers 
      - run: docker build -t abc/multi-client ./client
      - run: docker build -t abc/multi-nginx ./nginx
      - run: docker build -t abc/multi-server ./server
      - run: docker build -t abc/multi-worker ./worker

      #login to docker hub
      - run: echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin 
      # push to docker hub
      - run: docker push abc/multi-client
      - run: docker push abc/multi-nginx
      - run: docker push abc/multi-server
      - run: docker push abc/multi-worker